apiVersion: v1
kind: Service
metadata:
  name: {{ include "general-insurance.fullname" . }}
  labels:
    {{- include "general-insurance.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "general-insurance.selectorLabels" . | nindent 4 }}
