name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
       DOCKER_USER: ${{secrets.DOCKER_USER}}
       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vikrantdhir:$(date +%s)
      
    - name: Docker Push 
      run : docker push ${{secrets.DOCKER_USER}}/poc_repos
