# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven and Docker Build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: run file check
      run: ls /home/runner/work/gi/gi/target/gi-0.0.1-SNAPSHOT.jar 
    - name: find  dockerfile
      run: find . -name Dockerfile
    - name: find all files
      run: ls  
    - name: snapshot
      run: ls ./target/gi-0.0.1-SNAPSHOT.jar 

    - name: Build the Docker image
      run: docker build . --tag mastsurfeit/gi:latest    
      
      
    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
       username: ${{secrets.DOCKER_USER}}
       password: ${{secrets.DOCKER_PASSWORD}}
      
    - name: Docker Push 
      run : docker push ${{secrets.DOCKER_USER}}/gi:latest
